### PR TITLE
Add .gitignore and remove dist from repo

### PR DESCRIPTION
**Pull request by timstallmann**
@tobinbradley wondering if this makes sense to clean up the repo a bit -- this creates a `.gitignore`, and removes the `dist` directory. I created an additional gulp step `copy-misc-files` to deploy a few specific files from `src` to `dist` which aren't covered by the other gulp tasks. Consequently, local set-up now requires running `gulp datagen` as well as `gulp build`.

### CODE REVIEW

**Comment by timstallmann** [comment]
Ha -- looks like standard practice is to commit `node_modules` folder. I'm coming from the PHP world, so apologies for that! Will re-work...

**Comment by tobinbradley** [comment]
Oh no, you don't want to include node_modules. That's a bazillion files, so of which could be OS dependant or require local compilation. Better to let people npm install when they grab the repo. 

Thanks for doing this! I've been meaning to do the same thing for ages but never got around to it.

**Comment by timstallmann** [comment]
No prob! As a bit of context, I'm doing some development on the Durham dashboard with John Killeen, and trying to bring in some of your more recent updates into that codebase.

What would you think about even moving the data directory into a sub-repo so that the codebase was more place-independent?

**Comment by tobinbradley** [comment]
Just merged a fix for the fonts folder (added folder to ./src and copy-misc-files), otherwise everything seems to work perfectly. Thanks again!

**Comment by tobinbradley** [comment]
I think that's possible. It would require moving the config.js file to sit with the data as well, but since it contains a lot of local config information (map extent, tile sources, etc.) you'd want to do that anyway. Then you could have the main project's .gitignore ignore the data folder. It would require two git clone's to get started, but that probably isn't terrible. Hmm...

**Pull request merged**
