### PR TITLE
Abstract some stuff out so that data directory can be moved out of repo

### PR DESCRIPTION
**Pull request by timstallmann**
@tobinbradley let me know what you think -- I'm using [swig templates](https://paularmstrong.github.io/swig/docs/api/) for the index and report.html files. 

I wonder if it'd be possible to replace the underscore templating and use swig for that part as well, but it looks like those templates have more complex logic that swig might not support?

With this PR it should be possible to move data into a separate repo entirely and then swap in a separate data directory for the Durham dashboard. There are probably a few Mecklenburg-specific pieces of text in the `index.html` which I forgot to template out, but that can be done as we see them...

I'll leave actually moving data into a separate repo to you, since you'd have to create the repo under your git account.

### CODE REVIEW

**Comment by tobinbradley** [comment]
Tell me more about why you're using swig? With two web pages, neither of which are going be sharing any elements, I'm not sure what templating those pages gets us. Looks like what it's doing now is copying the file.

**Comment by timstallmann** [comment]
Hi @tobinbradley! It does look like a bit of overkill for just two files. I think the advantages are as follows:
* It moves most of the site-specific elements (title, menus, description text) into a separate json file which can be swapped out for other data dashboards -- my main goal here is to get this to a place where we can treat the Durham nbhd compass as a branch off of the Charlotte one and take advantage of each other's development work rather than having them developing along separate lines.
* The geography selectors in the index.html file are now generated dynamically from the `customGeography` variable in config.js rather than being hardcoded -- this also simplifies the index.html code a bit and makes it slightly easier to modify these
* Meta/header and footer elements are standardized across the two files as much as possible, which makes them a tiny bit more readable imo

That said, most of these could probably be implemented using a different approach, like the underscore templating that you're using elsewhere in index.html. I just happen to like swig because I'm familiar with TWIG templating already from the Drupal / PHP world.

**Comment by tobinbradley** [comment]
Sorry it took me a bit to get back on this. I can see the value of using some server-side templating. Thanks!

**Comment by tobinbradley** [comment]
FYI I just posted a change that moves the data folder out of the project entirely, and adds grabbing data to the Readme. The data folder was moved to the project root and is now ignored by git (so the git repo in a git repo doesn't lead to a singularity).

Also while I was at it I moved all the bower dependencies to node, so bower is no longer necessary.

**Comment by timstallmann** [comment]
Awesome! Thanks for the heads-up.

**Pull request merged**
